import mongoose from 'mongoose';

const commissionSchema = new mongoose.Schema({
    staff: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true
    },
    period: {
        month: {
            type: Number,
            required: true,
            min: 1,
            max: 12
        },
        year: {
            type: Number,
            required: true
        }
    },
    clinic: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Clinic',
        required: true,
        index: true
    },
    totalRevenue: {
        type: Number,
        required: true,
        default: 0
    },
    commissionRate: {
        type: Number,
        required: true,
        min: 0,
        max: 100,
        default: 0
    },
    commissionAmount: {
        type: Number,
        required: true,
        default: 0
    },
    bonuses: [{
        description: String,
        amount: Number
    }],
    deductions: [{
        description: String,
        amount: Number
    }],
    netAmount: {
        type: Number,
        required: true,
        default: 0
    },
    status: {
        type: String,
        enum: ['calculated', 'approved', 'paid'],
        default: 'calculated',
        index: true
    },
    approvedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    approvedAt: {
        type: Date
    },
    paidAt: {
        type: Date
    },
    paymentMethod: {
        type: String,
        enum: ['cash', 'transfer', 'check'],
        default: 'transfer'
    },
    notes: {
        type: String,
        trim: true
    }
}, {
    timestamps: true
});

// Compound indexes
commissionSchema.index({ staff: 1, 'period.year': -1, 'period.month': -1 }, { unique: true });
commissionSchema.index({ clinic: 1, status: 1 });
commissionSchema.index({ status: 1, 'period.year': -1, 'period.month': -1 });

// Calculate net amount before save
commissionSchema.pre('save', function (next) {
    const bonusTotal = this.bonuses.reduce((sum, b) => sum + (b.amount || 0), 0);
    const deductionTotal = this.deductions.reduce((sum, d) => sum + (d.amount || 0), 0);
    this.netAmount = this.commissionAmount + bonusTotal - deductionTotal;
    next();
});

// Static method to calculate commission for a staff member
commissionSchema.statics.calculateForStaff = async function (staffId, month, year, clinicId) {
    const Revenue = mongoose.model('Revenue');

    // Get start and end dates for the period
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    // Get total revenue generated by this staff member
    const revenueResult = await Revenue.aggregate([
        {
            $lookup: {
                from: 'appointments',
                localField: 'appointment',
                foreignField: '_id',
                as: 'appointmentData'
            }
        },
        {
            $match: {
                date: { $gte: startDate, $lte: endDate },
                status: 'confirmed',
                clinic: mongoose.Types.ObjectId(clinicId),
                'appointmentData.doctor': mongoose.Types.ObjectId(staffId)
            }
        },
        {
            $group: {
                _id: null,
                total: { $sum: '$amount' }
            }
        }
    ]);

    const totalRevenue = revenueResult[0]?.total || 0;

    // Get commission rate for this staff member (from user metadata or default)
    const User = mongoose.model('User');
    const staff = await User.findById(staffId);
    const commissionRate = staff?.metadata?.commissionRate || 10; // Default 10%

    const commissionAmount = (totalRevenue * commissionRate) / 100;

    return {
        totalRevenue,
        commissionRate,
        commissionAmount
    };
};

// Method to approve commission
commissionSchema.methods.approve = function (userId) {
    this.status = 'approved';
    this.approvedBy = userId;
    this.approvedAt = new Date();
    return this.save();
};

// Method to mark as paid
commissionSchema.methods.markAsPaid = function () {
    this.status = 'paid';
    this.paidAt = new Date();
    return this.save();
};

// Static method to get commissions by period
commissionSchema.statics.getByPeriod = function (month, year, filters = {}) {
    const query = {
        'period.month': month,
        'period.year': year,
        ...filters
    };

    return this.find(query)
        .populate('staff', 'profile email role')
        .populate('clinic', 'name')
        .populate('approvedBy', 'profile email');
};

export default mongoose.model('Commission', commissionSchema);
