import Invoice from '../models/Invoice.js';
import Bill from '../models/Bill.js';
import Clinic from '../models/Clinic.js';
import Patient from '../models/Patient.js';
import asyncHandler from 'express-async-handler';
// Removed html-pdf import as generation is frontend-side

// @desc    Get all invoices
// @route   GET /api/owner/invoices
// @access  Private/Owner
export const getInvoices = asyncHandler(async (req, res) => {
    const {
        status,
        paymentStatus,
        startDate,
        endDate,
        patientId,
        clinicId,
        page = 1,
        limit = 10
    } = req.query;

    const query = {};

    // Filters
    if (status) query.status = status;
    if (paymentStatus) query.paymentStatus = paymentStatus;
    if (patientId) query.patient = patientId;
    if (clinicId) query.clinic = clinicId; // Owner might want to filter by clinic

    // Date Range Filter
    if (startDate && endDate) {
        query.issueDate = {
            $gte: new Date(startDate),
            $lte: new Date(endDate)
        };
    }

    const invoices = await Invoice.find(query)
        .populate('patient', 'profile.firstName profile.lastName user.email')
        .populate('clinic', 'name')
        .sort({ issueDate: -1 })
        .limit(limit * 1)
        .skip((page - 1) * limit);

    const count = await Invoice.countDocuments(query);

    // Calculate Summary Stats for the filtered view
    const stats = await Invoice.aggregate([
        { $match: query },
        {
            $group: {
                _id: null,
                totalAmount: { $sum: '$totalAmount' },
                totalPaid: { $sum: '$paidAmount' },
                count: { $sum: 1 }
            }
        }
    ]);

    res.status(200).json({
        success: true,
        data: invoices,
        pagination: {
            total: count,
            page: Number(page),
            pages: Math.ceil(count / limit)
        },
        stats: stats[0] || { totalAmount: 0, totalPaid: 0, count: 0 }
    });
});

// @desc    Get Invoice Stats
// @route   GET /api/owner/invoices/stats
// @access  Private/Owner
export const getInvoiceStats = asyncHandler(async (req, res) => {
    const { startDate, endDate, clinicId } = req.query;

    const start = startDate ? new Date(startDate) : new Date(new Date().setMonth(new Date().getMonth() - 1));
    const end = endDate ? new Date(endDate) : new Date();

    const stats = await Invoice.getStats(start, end, clinicId ? { clinic: clinicId } : {});

    res.status(200).json({
        success: true,
        data: stats
    });
});

// @desc    Get single invoice
// @route   GET /api/owner/invoices/:id
// @access  Private/Owner
export const getInvoiceById = asyncHandler(async (req, res) => {
    const invoice = await Invoice.findById(req.params.id)
        .populate('patient')
        .populate('clinic')
        .populate('insuranceProvider');

    if (!invoice) {
        res.status(404);
        throw new Error('Invoice not found');
    }

    res.status(200).json({
        success: true,
        data: invoice
    });
});

// @desc    Create invoice
// @route   POST /api/owner/invoices
// @access  Private/Owner
export const createInvoice = asyncHandler(async (req, res) => {
    const {
        patient,
        clinic,
        items,
        dueDate,
        notes,
        insuranceProvider,
        status = 'draft'
    } = req.body;

    // Calculate totals
    const subtotal = items.reduce((acc, item) => acc + (item.quantity * item.unitPrice), 0);
    // Simple logic for tax/discount (could be enhanced)
    const tax = req.body.tax || 0;
    const discount = req.body.discount || 0;
    const totalAmount = subtotal + tax - discount;

    const invoice = await Invoice.create({
        patient,
        clinic,
        items,
        subtotal,
        tax,
        discount,
        totalAmount,
        dueDate,
        notes,
        insuranceProvider,
        status,
        isAutoGenerated: false
    });

    res.status(201).json({
        success: true,
        data: invoice
    });
});

// @desc    Generate Invoice from Bill
// @route   POST /api/owner/invoices/generate-from-bill
// @access  Private/Owner
export const generateInvoiceFromBill = asyncHandler(async (req, res) => {
    const { billId } = req.body;

    const bill = await Bill.findById(billId).populate('appointment');
    if (!bill) {
        res.status(404);
        throw new Error('Bill not found');
    }

    // Check if invoice already exists
    const existingInvoice = await Invoice.findOne({ billReference: billId });
    if (existingInvoice) {
        res.status(400);
        throw new Error('Invoice already exists for this bill');
    }

    // Map Bill items to Invoice items (Assuming bill might represent a single consultation/procedure)
    // If Bill structure is simple check appointment details
    const items = [{
        description: `Medical Service - ${bill.appointment?.type || 'Consultation'}`,
        quantity: 1,
        unitPrice: bill.totalAmount, // Assuming simple mapping
        total: bill.totalAmount
    }];

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30); // Default 30 days term

    const invoice = await Invoice.create({
        patient: bill.patient,
        clinic: bill.clinic || bill.appointment?.clinic,
        billReference: billId,
        items,
        subtotal: bill.totalAmount,
        totalAmount: bill.totalAmount,
        dueDate,
        status: 'draft',
        isAutoGenerated: true,
        generatedFrom: 'bill'
    });

    res.status(201).json({
        success: true,
        data: invoice
    });
});

// @desc    Update Invoice
// @route   PATCH /api/owner/invoices/:id
// @access  Private/Owner
export const updateInvoice = asyncHandler(async (req, res) => {
    const invoice = await Invoice.findById(req.params.id);

    if (!invoice) {
        res.status(404);
        throw new Error('Invoice not found');
    }

    if (invoice.status === 'paid' || invoice.status === 'cancelled') {
        res.status(400);
        throw new Error('Cannot update final invoice');
    }

    const updatedInvoice = await Invoice.findByIdAndUpdate(
        req.params.id,
        req.body,
        { new: true, runValidators: true }
    );

    res.status(200).json({
        success: true,
        data: updatedInvoice
    });
});

// @desc    Record Payment
// @route   POST /api/owner/invoices/:id/payment
// @access  Private/Owner
export const recordPayment = asyncHandler(async (req, res) => {
    const { amount, method, reference, notes } = req.body;

    const invoice = await Invoice.findById(req.params.id);
    if (!invoice) {
        res.status(404);
        throw new Error('Invoice not found');
    }

    await invoice.recordPayment(amount, method, reference, notes);

    res.status(200).json({
        success: true,
        data: invoice,
        message: 'Payment recorded successfully'
    });
});

// @desc    Send Invoice (Email)
// @route   PATCH /api/owner/invoices/:id/send
// @access  Private/Owner
export const sendInvoice = asyncHandler(async (req, res) => {
    const invoice = await Invoice.findById(req.params.id).populate('patient');

    if (!invoice) {
        res.status(404);
        throw new Error('Invoice not found');
    }

    // Mock Email Sending
    // In real app: await emailService.sendInvoice(invoice);
    console.log(`Sending invoice ${invoice.invoiceNumber} to ${invoice.patient?.user?.email}`);

    await invoice.markAsSent();

    res.status(200).json({
        success: true,
        message: 'Invoice sent successfully',
        data: invoice
    });
});

// @desc    Delete Invoice
// @route   DELETE /api/owner/invoices/:id
// @access  Private/Owner
export const deleteInvoice = asyncHandler(async (req, res) => {
    const invoice = await Invoice.findById(req.params.id);

    if (!invoice) {
        res.status(404);
        throw new Error('Invoice not found');
    }

    if (invoice.status !== 'draft') {
        res.status(400);
        throw new Error('Can only delete draft invoices. Cancel others instead.');
    }

    await invoice.deleteOne();

    res.status(200).json({
        success: true,
        message: 'Invoice deleted'
    });
});
