import RecurringPayment from '../models/RecurringPayment.js';
import Invoice from '../models/Invoice.js';
import asyncHandler from 'express-async-handler';

// @desc    Get all recurring payments
// @route   GET /api/owner/recurring-payments
// @access  Private/Owner
export const getRecurringPayments = asyncHandler(async (req, res) => {
    const { status, patientId, clinicId } = req.query;

    const query = {};
    if (status) query.status = status;
    if (patientId) query.patient = patientId;
    if (clinicId) query.clinic = clinicId;

    const payments = await RecurringPayment.find(query)
        .populate('patient', 'profile.firstName profile.lastName')
        .populate('clinic', 'name')
        .sort({ nextPaymentDate: 1 });

    res.status(200).json({
        success: true,
        data: payments
    });
});

// @desc    Create recurring payment
// @route   POST /api/owner/recurring-payments
// @access  Private/Owner
export const createRecurringPayment = asyncHandler(async (req, res) => {
    const {
        patient,
        clinic,
        frequency,
        startDate,
        endDate,
        amount,
        description,
        category,
        paymentMethod,
        autoInvoice,
        notifyBeforeDays
    } = req.body;

    // First nextPaymentDate is startDate
    const nextPaymentDate = startDate || new Date();

    const recurringPayment = await RecurringPayment.create({
        patient,
        clinic,
        frequency,
        startDate: startDate || new Date(),
        endDate,
        nextPaymentDate,
        amount,
        description,
        category,
        paymentMethod,
        autoInvoice,
        notifyBeforeDays
    });

    res.status(201).json({
        success: true,
        data: recurringPayment
    });
});

// @desc    Update recurring payment
// @route   PATCH /api/owner/recurring-payments/:id
// @access  Private/Owner
export const updateRecurringPayment = asyncHandler(async (req, res) => {
    const recurringPayment = await RecurringPayment.findById(req.params.id);

    if (!recurringPayment) {
        res.status(404);
        throw new Error('Recurring payment plan not found');
    }

    const updatedPayment = await RecurringPayment.findByIdAndUpdate(
        req.params.id,
        req.body,
        { new: true, runValidators: true }
    );

    // Recalculate next date if frequency changed? 
    // Usually requires manual reset or complex logic. Use caution.

    res.status(200).json({
        success: true,
        data: updatedPayment
    });
});

// @desc    Toggle Status (Pause/Resume/Cancel)
// @route   PATCH /api/owner/recurring-payments/:id/status
// @access  Private/Owner
export const updateRecurringStatus = asyncHandler(async (req, res) => {
    const { status } = req.body; // 'paused', 'active', 'cancelled'
    const payment = await RecurringPayment.findById(req.params.id);

    if (!payment) {
        res.status(404);
        throw new Error('Recurring payment not found');
    }

    if (status === 'paused') await payment.pause();
    else if (status === 'active') await payment.resume();
    else if (status === 'cancelled') await payment.cancel();
    else {
        res.status(400);
        throw new Error('Invalid status');
    }

    res.status(200).json({
        success: true,
        data: payment
    });
});

// @desc    Process Due Payments (Cron Trigger)
// @route   POST /api/owner/recurring-payments/process
// @access  Private/Owner (or System Admin)
export const processDuePayments = asyncHandler(async (req, res) => {
    const duePayments = await RecurringPayment.getDuePayments();

    const results = {
        processed: 0,
        errors: 0,
        details: []
    };

    for (const payment of duePayments) {
        try {
            // Logic to create invoice automatically 
            let invoiceId = null;

            if (payment.autoInvoice) {
                const dueDate = new Date();
                dueDate.setDate(dueDate.getDate() + 7); // Invoice due in 7 days

                const invoice = await Invoice.create({
                    patient: payment.patient._id,
                    clinic: payment.clinic._id,
                    items: [{
                        description: payment.description,
                        quantity: 1,
                        unitPrice: payment.amount,
                        total: payment.amount
                    }],
                    subtotal: payment.amount,
                    totalAmount: payment.amount,
                    dueDate,
                    status: 'sent', // Assume sent immediately
                    isAutoGenerated: true,
                    generatedFrom: 'recurring_payment',
                    notes: `Auto-generated from Recurring Payment Plan: ${payment._id}`
                });
                invoiceId = invoice._id;
            }

            // Mock payment processing (in reality call Stripe/Payment Gateway)
            // Assuming simplified flow: If invoice created, it is Pending. 
            // If payment method is 'credit_card' & stored, we would charge it.

            // For now, we update the recurring payment schedule as 'success' in generating the cycle
            await payment.processPayment(invoiceId, 'success');

            results.processed++;
            results.details.push({ id: payment._id, status: 'success', invoiceId });

        } catch (error) {
            console.error(`Error processing recurring payment ${payment._id}:`, error);
            await payment.processPayment(null, 'failed', error.message);
            results.errors++;
            results.details.push({ id: payment._id, status: 'failed', error: error.message });
        }
    }

    res.status(200).json({
        success: true,
        results
    });
});
